import {
  FirestoreRulesAstKind,
  FirestoreRulesFunctionAst,
  FirestoreRulesMatchAst,
  FirestoreRulesRootAst,
  FirestoreRulesServiceAst,
} from './rules-ast'

export interface RenderRulesConfig {
  indent?: string
}

export const renderRules = (
  rules: FirestoreRulesRootAst,
  config: RenderRulesConfig,
): string => {
  const { indent = '  ' } = config

  return (
    [
      `// Generated by GraphQL Firestore Rules`,
      `rules_version = \"${rules.version}\"`,
      renderService(rules.service, { indent }),
    ].join('\n') + '\n'
  )
}

const renderService = (
  service: FirestoreRulesServiceAst,
  config: Required<RenderRulesConfig>,
): string => {
  return [
    `service cloud.firestore {`,
    ...service.children
      .flatMap((child) => renderMatch(child, config).split('\n'))
      .map((v) => `${config.indent}${v}`),
    `}`,
  ].join('\n')
}

const renderMatch = (
  match: FirestoreRulesMatchAst,
  config: Required<RenderRulesConfig>,
): string => {
  return [
    `match ${match.target} {`,
    ...match.children
      .flatMap((child) =>
        (child.kind === FirestoreRulesAstKind.MATCH
          ? renderMatch(child, config)
          : renderFunction(child, config)
        ).split('\n'),
      )
      .map((v) => `${config.indent}${v}`),
    ...Object.entries(match.allow || {}).map(([key, value]) => {
      if (typeof value === 'string') {
        return `${config.indent}allow ${key}: if ${value}`
      } else if (value.length === 1) {
        return `${config.indent}allow ${key}: if ${value[0]}`
      } else {
        return [
          `${config.indent}allow ${key}: if ${value[0]}`,
          ...value
            .slice(1)
            .map((v) => `${config.indent}               ${config.indent}${v}`),
        ].join('\n')
      }
    }),
    `}`,
  ].join('\n')
}

const renderFunction = (
  functionAst: FirestoreRulesFunctionAst,
  config: Required<RenderRulesConfig>,
): string => {
  const statements =
    typeof functionAst.statement === 'string'
      ? [`${config.indent}return ${functionAst.statement}`]
      : [
          `${config.indent}return (`,
          ...functionAst.statement.map(
            (v) => `${config.indent}${config.indent}${v}`,
          ),
          `${config.indent})`,
        ]
  return [
    `function ${functionAst.name}(${functionAst.args.join(', ')}) {`,
    ...statements,
    `}`,
  ].join('\n')
}
