import { PluginFunction, Types } from '@graphql-codegen/plugin-helpers'
import { transformSchemaAST } from '@graphql-codegen/schema-ast'
import { GraphQLSchema, print, visit } from 'graphql'
import { FirestoreSchemaPluginConfig } from './config'
import { FirestoreSchemaVisitor } from './visitor'

export const plugin: PluginFunction<
  FirestoreSchemaPluginConfig,
  Types.ComplexPluginOutput
> = (
  schema: GraphQLSchema,
  documents: Types.DocumentFile[],
  config: FirestoreSchemaPluginConfig,
) => {
  const { schema: _schema, ast } = transformSchemaAST(schema, config)

  const visitor = new FirestoreSchemaVisitor(schema, config)

  visit(ast, visitor)

  return {
    prepend: [
      `# This file was automatically generated by @firebase-graphql/graphql-codegen-firestore-schema.`,
      `# Do not modify this file by hand.`,
      `# If you have any issues, please report them to https://github.com/YutaUra/firebase-graphql/issues`,
      `\n`,
    ],
    content: print(visitor.buildSchema),
  }
}
